version: '3.7'

services:
    jho-tech:
        build:
            context: '.'
            args:
                uid: ${UID}
        container_name: jho-tech
        restart: unless-stopped
        environment:
            - APACHE_RUN_USER=#${UID}
            - APACHE_RUN_GROUP=#${UID}
            - VITE_HOST=0.0.0.0
        volumes:
            - .:/var/www/html
            - /var/www/html/node_modules
        ports:
            - 8080:80
            - 5173:5173
        networks:
            - jho-tech-network
        depends_on:
            - jho-tech-db
            - elasticsearch

    jho-tech-db:
        image: mysql:8.0.32
        container_name: jho-tech-db
        restart: unless-stopped
        ports:
            - "3307:3306"
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=123456
            - MYSQL_DATABASE=jho_tech
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=123456
        networks:
            - jho-tech-network

    jho-tech-phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: jho-tech-phpmyadmin
        restart: unless-stopped
        ports:
            - "8386:80"
        environment:
            - PMA_HOST=jho-tech-db
            - MYSQL_ROOT_PASSWORD=123456
            - MYSQL_USER=admin
        networks:
            - jho-tech-network

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
        container_name: elasticsearch
        restart: unless-stopped
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ports:
            - "9200:9200"
        networks:
            - jho-tech-network
        volumes:
            - elasticsearch_data:/usr/share/elasticsearch/data

    kibana:
        image: docker.elastic.co/kibana/kibana:8.12.0
        container_name: kibana
        restart: unless-stopped
        ports:
            - "5601:5601"
        environment:
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
        depends_on:
            - elasticsearch
        networks:
            - jho-tech-network

networks:
    jho-tech-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
    elasticsearch_data:
        driver: local
